# Generated by Django 4.0.6 on 2022-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Date')),
                ('sunny', models.IntegerField(default=0)),
                ('rainny', models.IntegerField(default=0)),
                ('snow', models.IntegerField(default=0)),
            ],
        ),
    ]
